# Usa uma imagem oficial do OpenJDK com Maven embutido
FROM maven:3.9.6-eclipse-temurin-21

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copia apenas os arquivos necessários para baixar as dependências primeiro (melhora cache do Docker)
COPY pom.xml ./
RUN mvn dependency:go-offline -B

# Agora copia o restante do código-fonte
COPY src/ src/

# Compila a aplicação sem rodar testes
RUN mvn package -DskipTests

# Expõe a porta 8080
EXPOSE 8080

# Executa a aplicação
CMD ["java", "-jar", "target/user-auth-0.0.1-SNAPSHOT.jar"]
